### ISSUE TITLE
CLI shell completion

### ISSUE THREAD

**Issue by fishinthecalculator** [Tech-Workers-Coalition-Italia/mobilizon-reshare#114]
https://click.palletsprojects.com/en/8.0.x/shell-completion/

**Comment by chobeat** [comment]
I started playing with it the other day. It's not clear how to auto-install the completion when installing the package. I don't think it's possible in python

**Comment by fishinthecalculator** [comment]
+1. I tried a couple of times following those instructions and i didn't manage to get anything out of it. I think traditionally things like shell completion scripts are distributed by distros package managers.

Right now we can easily bundle them in the Docker image we distribute, whenever we'll have a Debian/Fedora/Arch/whatever package we'll review any required changes.
