### ISSUE TITLE
Make `Event.mobilizon_id` a proper UUIDField

### ISSUE THREAD

**Issue by chobeat** [Tech-Workers-Coalition-Italia/mobilizon-reshare#38]
It should be unique
It should have a reference to the instance it came from (link? some other Mobilizon instance id?)
Event class should have a reference to the `internal_id` and not only `mobilizon_id`. The `internal_id`should be used to identify the events in our system

**Comment by tinoilcotechino** [comment]
We are already good:
- mobilizon_id is an UUID: https://github.com/Tech-Workers-Coalition-Italia/mobilizon-bots/blob/master/mobilizon_bots/mobilizon/events.py#L38
- we already track mobilizon's event url: https://github.com/Tech-Workers-Coalition-Italia/mobilizon-bots/blob/master/mobilizon_bots/mobilizon/events.py#L37

One thing we could do is make the mobilizon_id in the db an actual `UUIDField`
