### ISSUE TITLE
Use `.secrets.toml` to store secrets

### ISSUE THREAD

**Issue by tinoilcotechino** [Tech-Workers-Coalition-Italia/mobilizon-reshare#45]
Dynaconf supports loading secrets from a different file. We already defined it in config.py, we just need to move secrets over there.

**Comment by chobeat** [comment]
makes sense. I would put into the secrets all the information relevant to credentials for every publisher and notifier, including target informations like the chat_id for telegram. I would keep together the whole block so that you don't have to jump back and forth between two files
